apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jewelhub-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - jewelhub
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s