import logging
import os
from datetime import datetime
from elasticsearch import Elasticsearch

logger = logging.getLogger(__name__)

ES_URL = os.getenv(
    'ELASTICSEARCH_URL',
    'http://elasticsearch-master.logging:9200'
)

def format_postmortem(alert, analysis):
    try:
        timestamp = datetime.utcnow().strftime(
            '%Y-%m-%d %H:%M:%S UTC'
        )

        postmortem = f"""
# Incident Postmortem
**Generated by SteadyStackAI** 🤖

## Incident Details
| Field | Value |
|-------|-------|
| Alert | {alert['name']} |
| Service | {alert['service']} |
| Severity | {alert['severity']} |
| Detected | {timestamp} |
| Time Window | Last {alert['time_window']['duration_mins']} mins |

## Summary
{alert.get('summary', 'N/A')}

## AI Analysis
{analysis}

---
*Auto-generated by SteadyStackAI AI Layer*
*Powered by Claude AI + Prometheus + Elasticsearch*
"""
        # Save to Elasticsearch
        save_to_elasticsearch(alert, analysis, postmortem)

        logger.info("✅ Postmortem formatted and saved!")
        return postmortem

    except Exception as e:
        logger.error(f"Postmortem error: {str(e)}")
        return f"Postmortem generation failed: {str(e)}"


def save_to_elasticsearch(alert, analysis, postmortem):
    try:
        es = Elasticsearch([ES_URL])

        doc = {
            "@timestamp": datetime.utcnow().isoformat(),
            "alert_name": alert['name'],
            "service": alert['service'],
            "severity": alert['severity'],
            "summary": alert.get('summary', ''),
            "analysis": analysis,
            "postmortem": postmortem,
            "type": "postmortem"
        }

        es.index(
            index="steadystackai-postmortems",
            body=doc
        )

        logger.info(
            "✅ Postmortem saved to Elasticsearch!"
        )

    except Exception as e:
        logger.error(
            f"Failed to save postmortem: {str(e)}"
        )