import logging
from datetime import datetime

logger = logging.getLogger(__name__)

def format_postmortem(alert, analysis):
    """
    Format incident analysis as postmortem
    """
    try:
        timestamp = datetime.utcnow().strftime(
            '%Y-%m-%d %H:%M:%S UTC'
        )

        postmortem = f"""
# Incident Postmortem
**Generated by SteadyStackAI** 🤖

## Incident Details
| Field | Value |
|-------|-------|
| Alert | {alert['name']} |
| Service | {alert['service']} |
| Severity | {alert['severity']} |
| Detected | {timestamp} |
| Time Window | Last {alert['time_window']['duration_mins']} mins |

## Summary
{alert.get('summary', 'N/A')}

## AI Analysis
{analysis}

---
*Auto-generated by SteadyStackAI AI Layer*
*Powered by Claude AI + Prometheus + Elasticsearch*
"""

        logger.info("✅ Postmortem formatted!")
        return postmortem

    except Exception as e:
        logger.error(
            f"Postmortem error: {str(e)}"
        )
        return f"Postmortem generation failed: {str(e)}"